//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p3p1_bolsa_trabajo_new.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class p3p1BolsaTrabajoEntitiesCategoriaOferta : DbContext
    {
        public p3p1BolsaTrabajoEntitiesCategoriaOferta()
            : base("name=p3p1BolsaTrabajoEntitiesCategoriaOferta")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoriaOfertaEmpleo> categoriaOfertaEmpleos { get; set; }
        public virtual DbSet<Oferta> Ofertas { get; set; }
    }
}
