//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p3p1_bolsa_trabajo_new.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oferta
    {
        public int id_ofertas { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_posteo { get; set; }
        public bool activo { get; set; }
        public int id_categoria_ofertas { get; set; }
        public string ubicacion { get; set; }
        public string posicion { get; set; }
        public string nombre_empresa { get; set; }
    
        public virtual categoriaOfertaEmpleo categoriaOfertaEmpleo { get; set; }
    }
}
