//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p3p1_bolsa_trabajo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        public int id_usuarios { get; set; }
        [Required(ErrorMessage = "Este campo es necesario")]
        [DisplayName("Email")]
        public string email { get; set; }
        [Required(ErrorMessage = "Este campo es necesario")]
        [DisplayName("Contraseña")]
        [DataType(DataType.Password)]
        public string password_usuario { get; set; }
        [DataType(DataType.Password)]
        [DisplayName("Confirmar Contraseña")]
        [Compare("password_usuario")]
        public string confirm_password { get; set; }
        [Required(ErrorMessage = "Este campo es necesario")]
        public string rol { get; set; }
    }
}
